resources:
  - url: http://127.0.0.1:5000/boilerplate-card.js
    type: module
views:
  - cards:
      - type: custom:lovelace-body-miscale-card
        name: Lovelace body Miscale Card Development
        entity: sun.sun
        test_gui: true
